repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0  # Use the ref you want to point at
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
-   repo: https://github.com/nedtaylor/fortran-format-hooks
    rev: 74c5a55b724bf26ee9ff172529eab52e02c555e5
    hooks:
    -   id: check-fortran-indentation
        args: [--line-length=80]
